project:
  type: website

website:
  title: "Quarto Website"

  navbar:
    background: secondary
    style: "floating"
    search: true

    left:
      - text: " "
        icon: house
        file: index.qmd
      - icon: github
        href: https://github.com/
    
    right:    
      - sidebar:python
      - sidebar:ML
      - sidebar:NN
      - sidebar:Colab
      - sidebar:project
      - sidebar:about

  sidebar:
    - id: "python"
      title: "Python"
      border: true
      collapse-level: 1
      background: light
      search: true
      style: "floating"
      contents:
        - text: "Python"  
        - text: "---"
        - section: "Python: concepts"
          contents:
            - python/python.qmd
        - text: "---"
        - section: "Data analysys"
          contents:
            - python/data_analysis.qmd
            - python/numpy.ipynb
            - python/pandas.ipynb           
            - python/matplotlib.ipynb
            - python/seaborn.ipynb
            - python/scikit-learn.ipynb
            - python/tensorflow.ipynb

    - id: "ML"
      title: "Machine Learning"
      border: true
      collapse-level: 1
      background: light
      search: true
      style: "floating"
      contents:
        - text: "Machine Learning"  
        - text: "---"
        - section: "ML: concepts"
          contents:
            - machine_learning/machine_learning.qmd
        - text: "---"
        - section: "Supervised learning"
          contents:
            - machine_learning/supervised_intro.ipynb

    - id: "NN"
      title: "Neural Networks"
      contents:
        - text: "Neural Networks"  
        - text: "---"
        - section: "NN: concepts"
          contents:
            - neuralNetworks.qmd

    - id: "Colab"
      title: "Google Colab"
      contents:
        - text: "Google Colab"  
        - text: "---"
        - section: "Colab: concepts"
          contents:

    - id: "project"
      title: "Head-count project"
      contents:
        - text: "Head-count project"  
        - text: "---"
        - section: "Project: concepts"
          contents:
            - Proyecto_HeadCounting.ipynb

    - id: "about"
      title: "About"
      contents:
        - text: "About"
        - text: "---"
        - section: "About me and this site"
          

        
            


      
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



