project:
  type: website

website:
  title: "Quarto Website"
  navbar:
    left:
      - href: index.qmd
        text: " "
        icon: house
      - python.qmd
      - text: "Machine Learning"
        menu:
          - href: neuralNetworks.qmd
            text: Neural Networks
            menu:  
            - href: convulsionalNeuralNetworks.qmd
              text: Convulsional Neural Networks
      - text: "Project head counting"
        href: Proyecto_HeadCounting.ipynb
            

    right:
      - about.qmd
      
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



